baseurl: /open-standards

theme: jekyll-theme-minimal

# Collections are groups of pages
collections:
  standards:
    output: true
    permalink: /standards/:path/
  meetings:
    output: true
    permalink: /meetings/:path/
